---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter

- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus

- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - grafana
